// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    'Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY in environment. Add them to .env or .env.local'
  );
}

const authOptions = {
  // only use localStorage in the browser (avoid SSR/runtime errors)
  storage: typeof window !== 'undefined' ? localStorage : undefined,
  persistSession: true,
  autoRefreshToken: true,
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: authOptions,
});

/**
 * Wrapper around supabase.auth.signInWithPassword to normalize return shape
 * and centralize logging/error handling.
 */
export async function signInWithPassword(email: string, password: string) {
  try {
    const res = await supabase.auth.signInWithPassword({ email, password });
    // Normalize results: { data, error }
    return { data: res.data ?? null, error: res.error ?? null };
  } catch (err) {
    console.error('supabase signInWithPassword unexpected error:', err);
    return { data: null, error: err as unknown };
  }
}